console.log('load _tone_1180_FluidR3_GM_sf2_file');
var _tone_1180_FluidR3_GM_sf2_file={
	zones: [
		// ji: 08.2021: This block commented out since its not contiguous with the rest
		//{
		//	midi:118
		//	,originalPitch:4100
		//	,keyRangeLow:0
		//	,keyRangeHigh:127
		//	,loopStart:-1
		//	,loopEnd:-2
		//	,coarseTune:0
		//	,fineTune:0
		//	,sampleRate:44100
		//	,ahdsr:false
		//	,file: (deleted)
		//	,anchor:0.05163265
		//	//_tone.Electronic_Tom_R_
		//}
		//,{
		{
			midi:118
			,originalPitch:4100
			,keyRangeLow:0
			,keyRangeHigh:64
			,loopStart:98
			,loopEnd:500
			,coarseTune:-5
			,fineTune:0
			,sampleRate:44100
			,ahdsr:true
			,file:'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU3LjcyLjEwMQAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAAEewDi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi//////////////////////////////////////////////////////////////////8AAAAATGF2YzU3Ljk2AAAAAAAAAAAAAAAAJARmAAAAAAAABHvC/JfpAAAAAAD/+9DEAAAMOCNHVYAAK2WnaD8/kIgAAAi79bbkU3aBgjQw2KMwENHEjEPy+np6enp8wwAAADTYeHv/AAEf8cP//AHeZ/+Bv/45n/+f/+YA74AGH/mHgAjgABh4eHh4AAAAABh4eHh4AAGQEYe/5wAR/5j//3f/7AAICKYGCJyJit0ko0GwuCMO7ACjAqAGE4FgJXMGGABzLNwVEwFgBUMA+AKQaAEGAkgAr+mA4gOpgQwCoAgAoss8ABAEBIHUMBhAN3Ba6hwTjOJQIIWFfZ3matZpZ0BCIoO1KYzDNBW1SvIuxdjqPs5TWoi/u/wyvwUXUSQSvbBDNaNRqrS47/+6gRdcjwYnD8ZrU0qq0tL////99Y7E4u/7W4Hyyy3jjrLL/////+zE4u/GNO7k53GzjrLLHHHWX///////GJZykpLGFJYCwVBUs9v1+A58ufSqAYACUnOIA5mlZuIZxIJtlZmhaXLxKZKAqCrFYizlyXJh2y5pEAkSJEiRqv5kiRI0FHYgoUFHfGCgob/AoKCv+EFBQL/AoJBXfkCgor6QUFFf4KCgpv+Cgo3/6DBR34hQUN/4QUFf+QUFBP/CCgUV/AkFBf+LTEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sgxPkDzpxLPv2jACgAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ=='
			,anchor:0.00226757
			//_tone.Sine_Wave_A1
		}
		,{
			midi:118
			,originalPitch:6500
			,keyRangeLow:65
			,keyRangeHigh:88
			,loopStart:52
			,loopEnd:252
			,coarseTune:-5
			,fineTune:0
			,sampleRate:44100
			,ahdsr:true
			,file:'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU3LjcyLjEwMQAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAAEyQDU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU//////////////////////////////////////////////////////////////////8AAAAATGF2YzU3Ljk2AAAAAAAAAAAAAAAAJAWSAAAAAAAABMk2Cu4vAAAAAAD/+9DEAAAMnCFPVYAALghIKP8/4hgAAAi79ZbgMNe6aBgMaEGYhaBTR3JfT09PT09OHgAAAGKxw8f/gAA7+h5//gI/D//Af/9DP//P//wd/+f//hgAAAAHh4eHhgAAAAAHh4eHhgAAAAgPDw8PSAAjAQHn/+Bn/7//9AFANkdAUgcAjm8SGJUOiYGAxDsRhQgJKYKiC7GATgN5zMnt2cW8lQGB8ASpgEYBMYAwAXGAFgCBpr8JOYHIFAGAlgIhgIIB0YAIAMjwAsYv2MfGF1FS4iADAwAI0AMlwZWCL5klDHAQAFfSgxeNjbCDDjFhMK4W8xagl0vnBZyw12VLWhMEMLEVIwYwlhwHkwAw4HCZ0u6CXJa4wN4GdO6YKYUw0HsYJwMpgFABmBaB8/s1Go1S0sDyOHI3KZUYAAHZgDAPhgBibKioGAJh2ajUau0spop2fjFyhyC4BCGTK18LyXshNpo1GqtLLblNTS6il9PKLtLanIZjz0vrJoappS3arS0uVNTY0tnVqxT1K1W/fsU924+0/Z1LnRhmkrzMtrY2ccsu5485l/Pszs/LKlfKmvS+3Ur0tp9pVXkkqnojVrR2U3qbtL////////r/3///7/9f+P//////////////////wFKrfNU0RlNSvVsxKmu0E1flONaOym9TdpYknRZQAFKTk6YhKhNlU2q2NBe6hPo0r1xeDUxBTUUzLjk5LjWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//tQxKODwyAnAxzwgCgAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg=='
			,anchor:0.00113379
			//_tone.Sine_Wave_A2
		}
		,{
			midi:118
			,originalPitch:8900
			,keyRangeLow:89
			,keyRangeHigh:127
			,loopStart:25
			,loopEnd:125
			,coarseTune:-5
			,fineTune:0
			,sampleRate:44100
			,ahdsr:true
			,file:'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU3LjcyLjEwMQAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAADxADW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tbW//////////////////////////////////////////////////////////////////8AAAAATGF2YzU3Ljk2AAAAAAAAAAAAAAAAJAYpAAAAAAAAA8Te2yfoAAAAAAD/+7DEAAAJvCFc7CzGIamJ6p2cJKUAJTut2664fVvQfbYKAMgi3gkwcBp2TTWGFBhRwu8u8o4pLyfOTmsc4aOLynZ84p0+uXlIgg/D8PKDCgws+XeUcUcQeJ4nhicn1vW9X9AKAASk5wqMRBJghdQ7eD1iCBmyYGrK2wF3mTXZhhz9YlQRZ1UlzVUW9Zr0ia9oXArgrwrxnRXRXDsjoLororwrwrxXiujeHZHYuxdCfC8J8V4rxvDum4m4vyfC+L83jfG8O6b1jj8n4/j+lbmvoJAAAQMZIIUgYCLaFKploqLKLKOsYVXXIw9nDW3AGBsgRnmkK1sssstBRAyqulVMQU1FMy45OS41VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7MMTSA8YITQMsJG5IAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ=='
			,anchor:0.00056689
			//_tone.Sine_Wave_A3
		}
	]
};
